### ISSUE TITLE
tgcalls.Stream is not a function

### ISSUE THREAD

**Issue by afeno** [tgcalls-next/tgcalls#8]
Hi,
I'm trying to create a basic test to try this library but I can't make it working.

This is my code taken from the README:
```
const { createReadStream } = require("fs");
const { Stream } = require("tgcalls-next");
const { TGCalls } = require("tgcalls-next");

const { TelegramClient } = require("telegram");
const { StringSession } = require("telegram/sessions");
const input = require("input"); // npm i input

const apiId = 123456;
const apiHash = "myhash";
const stringSession = new StringSession("");

const client = new TelegramClient(stringSession, apiId, apiHash, {connectionRetries: 5,});

(async () => {
  await client.start();

  const tgcalls = new TGCalls(client, 78901234);
  const audio_stream = new Stream({audio: createReadStream("audio.raw")},{video:true,});

  await tgcalls.Stream(audio_stream);
})();
```

And this is the error:
```
/home/ubuntu/tgcalls/test1.js:24
  await tgcalls.Stream(audio_stream);
                      ^

TypeError: tgcalls.Stream is not a function
    at /home/ubuntu/tgcalls/test1.js:24:17
```
What I am doing wrong?
Does anybody have a simple working example?

Thanks!

**Comment by rojvv** [comment]
It is `Stream`, not `stream`. Please think once about your problem before firing an issue.

**Comment by afeno** [comment]
Sorry @roj1512 . 
I admint that I don't have experience with nodejs but where do you see "stream" in my code?
I'm just using the example from the README and it looks like tgcall class doesn't have a method call Stream/stream. (as it is in the example).
I'm just trying to get a simple working code.
Thanks for your understanding and sorry if I am worng.

**Comment by abh80** [comment]
You absolutely correct @afeno he copied the code from somewhere, it is supposed to .start() after `joinVoiceCall` method
